# Generated by Django 2.1.7 on 2019-04-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20190403_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='age',
            new_name='newage',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='occupation',
            new_name='newoccupation',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='sex',
            new_name='newsex',
        ),
    ]
