# Generated by Django 2.1.7 on 2019-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20190403_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='newage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='info',
            name='newoccupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='newsex',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
