# Generated by Django 2.1.7 on 2019-04-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_auto_20190403_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='newage',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='newoccupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='newsex',
            new_name='sex',
        ),
    ]
